'''
Catherine Turner
8/11/19
https://projecteuler.net/ Problem 29
'''

# Return the sequence of distinct terms generated by a^b within the given ranges for a and b
def powerCombos(minA, maxA, minB, maxB):
    combos = []
    # Generate all a^b within provided ranges
    for a in range(minA, maxA+1):
        for b in range(minB, maxB+1):
            combos.append(a**b)
    # Sort list in numerical order
    combos.sort()
    # Remove repeated values, making list a sequence of distinct terms
    for combo in combos:
        while combos.count(combo) > 1:
            combos.remove(combo)
    return combos

print(len(powerCombos(2, 100, 2, 100)))
